services:
  mysql:
    image: mysql:latest
    container_name: inventorDB
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./initdb:/docker-entrypoint-initdb.d"